name: Digest cooldown

on:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "23 * * * *"
  workflow_dispatch:

permissions:
  statuses: write
  pull-requests: write
  contents: read

jobs:
  cooldown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./digest-cooldown
        with:
          cooldown-days: 3
